global:
  pattern: xray

  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

  datacenter:
    cloudProvider: PROVIDE_CLOUDPROVIDER # Not required for on-prem
    storageClassName: "ocs-storagecluster-cephfs" # Default filesystem storage used on on-prem cluster, can be changed by user
    region: PROVIDE_REGION # Not required for on-prem
    clustername: "" # Not required for on-prem, pattern uses on-prem cluster value instead
    domain: "" # Not required for on-prem, pattern uses on-prem cluster value instead

  xraylab:
    namespace: "xraylab-1"

    s3:
      # Values for S3 bucket access
      # bucketSource: "provide s3 bucket name where images are stored"
      bucketSource: "xray-image-store"
      # Bucket base name used for image-generator and image-server applications.
      bucketBaseName: "xray-source"

main:
  clusterGroupName: hub

# Example Configuration
  #datacenter:
  #  cloudProvider: aws
  #  storageClassName: gp2
  #  region: us-east-1
  #  clustername: example-sample
  #  domain: patterns.redhat.com

