apiVersion: batch/v1
kind: Job
metadata:
  name: create-prometheus-datasource-object
  namespace: {{ .Values.global.xraylab.namespace }}
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
      - image: {{ .Values.job.image }}
        command:
        - /bin/bash
        - -c
        - |
          #!/usr/bin/env bash
          TOKEN=$( oc get secret {{ .Values.global.xraylab.serviceAccountName }}-token -n xraylab-1 -o jsonpath='{.data.token}' | base64 --decode)
          cat <<EOF | oc create -f -
           apiVersion: grafana.integreatly.org/v1beta1
           kind: GrafanaDatasource
           metadata:
             name: prometheus-grafana-datasource
             namespace: {{ .Values.global.xraylab.namespace }}
           spec:
             instanceSelector:
               matchLabels:
                 dashboards: "grafana"
             datasource:
               basicAuthUser: internal
               access: proxy
               editable: true
               isDefault: false
               secureJsonData:
                 httpHeaderValue1: 'Bearer ${TOKEN}'
               name: prometheus
               url: 'https://thanos-querier.openshift-monitoring.svc.cluster.local:9091'
               jsonData:
                 httpHeaderName1: 'Authorization'
                 timeInterval: 5s
                 tlsSkipVerify: true
               type: prometheus
             name: grafana-prometheus-datasource.yaml
          EOF
        name: get-grafana-token
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccount: {{ .Values.global.xraylab.serviceAccountName }}
      terminationGracePeriodSeconds: 60