apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: {{ .Values.global.xraylab.serviceAccountName }}
    argocd.argoproj.io/sync-wave: '2'
  labels:
    argocd.argoproj.io/instance: xraylab-grafana-dashboards
  name: {{ .Values.global.xraylab.serviceAccountName }}-token
  namespace: xraylab-1
type: kubernetes.io/service-account-token